name: Security Vulnerability Report
description: Report a security vulnerability found in UnifyMail
title: "[Security]: "
labels: ["security", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        **IMPORTANT: For critical or sensitive vulnerabilities, please consider using [GitHub's private vulnerability reporting](https://github.com/TheDarkSkyXD/UnifyMail/security/advisories/new) instead of this public form.**

        Public issues are visible to everyone. If the vulnerability could be actively exploited before a fix is released, please report it privately.

  - type: checkboxes
    attributes:
      label: Guidelines
      description: Please ensure you've completed all of the following.
      options:
        - label: I have confirmed this is a security vulnerability and not a general bug (use the Bug Report template for non-security bugs).
          required: true
        - label: I have [searched the issue tracker](https://github.com/TheDarkSkyXD/UnifyMail/issues?q=is%3Aissue+sort%3Arelevance-desc) for open and closed issues that are similar to this vulnerability report, without success.
          required: true
        - label: I understand that this report will be publicly visible. For sensitive vulnerabilities, I should use [private reporting](https://github.com/TheDarkSkyXD/UnifyMail/security/advisories/new) instead.
          required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe do you consider this vulnerability?
      options:
        - Critical - Remote code execution, full system compromise
        - High - Data breach, authentication bypass, privilege escalation
        - Medium - Information disclosure, denial of service
        - Low - Minor information leak, requires unlikely conditions
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: What area of the application is affected?
      options:
        - Authentication / Credentials
        - Email Rendering / HTML Sanitization
        - Attachment Handling
        - Network / TLS / Encryption
        - Local Data Storage
        - Sync Engine
        - Plugin System
        - Auto-Update Mechanism
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: A clear and concise description of the security vulnerability. Explain what the vulnerability is and why it is a security concern.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the vulnerability.
      placeholder: |
        1. Configure '...'
        2. Send/receive an email with '...'
        3. Observe '...'
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: What is the potential impact of this vulnerability? What could an attacker achieve by exploiting it?
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Fix / Mitigation
      description: If you have a suggestion for how to fix or mitigate this vulnerability, please describe it here.

  - type: input
    id: version
    attributes:
      label: UnifyMail Version
      description: What version of UnifyMail is affected? You can find this in Help > About UnifyMail.
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system did you reproduce this on?
      options:
        - Windows
        - macOS
        - Linux
        - All / Platform Independent
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: |
        Add any other context, proof-of-concept code, screenshots, or references here.
        You may drag-and-drop files to attach them.
        **Do NOT include working exploits for critical vulnerabilities in public issues.**
