/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Full provider info returned by providerForEmail.
 *
 * Matches the MailProviderInfo TypeScript interface.
 */
export interface MailProviderInfo {
  identifier: string
  servers: ProviderServers
  domainMatch: Array<string>
  mxMatch: Array<string>
}

/**
 * Connection settings for a single IMAP/SMTP/POP server.
 *
 * Field names use snake_case in Rust; napi-rs auto-converts to camelCase for JavaScript
 * (connection_type → connectionType).
 */
export interface NetServiceInfo {
  hostname: string
  /** napi-rs maps u32 to JavaScript number safely. Do NOT use u16. */
  port: number
  connectionType: string
}

/**
 * Look up the mail provider for a given email address.
 *
 * - Returns a provider object when a domain-match is found.
 * - Returns null when the email is valid but no provider matches.
 * - Throws a JS Error when email is empty or missing '@'.
 */
export declare function providerForEmail(email: string): MailProviderInfo | null

/** Grouped server lists for a mail provider. */
export interface ProviderServers {
  imap: Array<NetServiceInfo>
  smtp: Array<NetServiceInfo>
  pop: Array<NetServiceInfo>
}

/**
 * Load additional providers from a JSON file and merge them into the existing set.
 *
 * File providers win on identifier conflict (file overrides embedded).
 * Newly-seen identifiers are appended.
 */
export declare function registerProviders(jsonPath: string): void

// ---------------------------------------------------------------------------
// IMAP connection testing (Phase 2)
// ---------------------------------------------------------------------------

/** Options for testIMAPConnection. */
export interface IMAPConnectionOptions {
  hostname: string
  port: number
  /** "tls" | "starttls" | "clear". Defaults to "tls". */
  connectionType?: string | null
  username?: string | null
  password?: string | null
  /** OAuth2 bearer token for XOAUTH2 SASL authentication. */
  oauth2Token?: string | null
}

/** Result of testIMAPConnection. The Promise ALWAYS resolves. */
export interface IMAPConnectionResult {
  success: boolean
  error?: string | null
  /** "connection_refused" | "timeout" | "tls_error" | "auth_failed" | "unknown" */
  errorType?: string | null
  /** Detected IMAP capabilities (e.g. "idle", "condstore"). Present only on success. */
  capabilities?: Array<string> | null
}

/**
 * Test an IMAP connection with the given settings.
 *
 * Returns a result object — never rejects. Wraps the operation in a 15-second timeout.
 */
export declare function testIMAPConnection(opts: IMAPConnectionOptions): Promise<IMAPConnectionResult>

// ---------------------------------------------------------------------------
// SMTP connection testing (Phase 3 Plan 01)
// ---------------------------------------------------------------------------

/** Options for testSMTPConnection. */
export interface SMTPConnectionOptions {
  hostname: string
  port: number
  /** "tls" | "starttls" | "clear". Defaults to "tls". */
  connectionType?: string | null
  username?: string | null
  password?: string | null
  /** OAuth2 bearer token for XOAUTH2 SASL authentication. */
  oauth2Token?: string | null
}

/** Result of testSMTPConnection. The Promise ALWAYS resolves. */
export interface SMTPConnectionResult {
  success: boolean
  error?: string | null
  /** "connection_refused" | "timeout" | "tls_error" | "auth_failed" | "unknown" */
  errorType?: string | null
}

/**
 * Test an SMTP connection with the given settings.
 *
 * Returns a result object — never rejects. Wraps the operation in a 15-second timeout.
 */
export declare function testSMTPConnection(opts: SMTPConnectionOptions): Promise<SMTPConnectionResult>

// ---------------------------------------------------------------------------
// Account validation (Phase 3 Plan 02)
// ---------------------------------------------------------------------------

/** IMAP sub-result within AccountValidationResult. */
export interface IMAPSubResult {
  success: boolean
  error?: string | null
  errorType?: string | null
  capabilities?: Array<string> | null
}

/** SMTP sub-result within AccountValidationResult. */
export interface SMTPSubResult {
  success: boolean
  error?: string | null
  errorType?: string | null
}

/** Server connection info. */
export interface ServerInfo {
  hostname: string
  port: number
}

/** Options for validateAccount. */
export interface ValidateAccountOptions {
  email: string
  imapHostname: string
  imapPort: number
  imapConnectionType?: string | null
  smtpHostname: string
  smtpPort: number
  smtpConnectionType?: string | null
  username?: string | null
  password?: string | null
  oauth2Token?: string | null
}

/** Full result of validateAccount. The Promise ALWAYS resolves. */
export interface AccountValidationResult {
  /** true only when both IMAP and SMTP succeed. */
  success: boolean
  /** Prefixed with "IMAP: " or "SMTP: ". IMAP takes priority when both fail. */
  error?: string | null
  /** Error type from the failing protocol. */
  errorType?: string | null
  /** Provider identifier from MX record matching, or null. */
  identifier?: string | null
  /** IMAP sub-result (always present). */
  imapResult: IMAPSubResult
  /** SMTP sub-result (always present). */
  smtpResult: SMTPSubResult
  /** IMAP server info (hostname + port from opts). */
  imapServer: ServerInfo
  /** SMTP server info (hostname + port from opts). */
  smtpServer: ServerInfo
}

/**
 * Validate an email account by testing IMAP and SMTP concurrently.
 *
 * Runs IMAP test, SMTP test, and MX DNS resolution via tokio::join!().
 * Total time = max(IMAP, SMTP, MX) — not their sum. 15-second timeout.
 */
export declare function validateAccount(opts: ValidateAccountOptions): Promise<AccountValidationResult>
