/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Full result of validateAccount.
 *
 * The Promise ALWAYS resolves — failures are encoded in success=false.
 */
export interface AccountValidationResult {
  /** true only when both IMAP and SMTP succeed */
  success: boolean
  /**
   * Top-level error: prefixed with "IMAP: " or "SMTP: " depending on which failed.
   * When both fail, IMAP takes priority.
   */
  error?: string
  /** Top-level errorType: from the failing protocol (IMAP takes priority). */
  errorType?: string
  /** Provider identifier from MX record matching, or None if no match. */
  identifier?: string
  /** IMAP sub-result (always present, never None). */
  imapResult: ImapSubResult
  /** SMTP sub-result (always present, never None). */
  smtpResult: SmtpSubResult
  /** IMAP server info (hostname + port from opts). */
  imapServer: ServerInfo
  /** SMTP server info (hostname + port from opts). */
  smtpServer: ServerInfo
}

/**
 * Options for testIMAPConnection.
 *
 * Field names use snake_case in Rust; napi-rs auto-converts to camelCase for
 * JavaScript (connection_type → connectionType, oauth2_token → oauth2Token).
 */
export interface ImapConnectionOptions {
  hostname: string
  /** Port number as u32 (napi-rs maps u32 to JavaScript number safely). */
  port: number
  /** Connection type: "tls" | "starttls" | "clear". Defaults to "tls" if absent. */
  connectionType?: string
  username?: string
  password?: string
  /** OAuth2 bearer token for XOAUTH2 SASL authentication. */
  oauth2Token?: string
}

/**
 * Result of testIMAPConnection.
 *
 * Extends the C++ IMAPConnectionResult with an optional `errorType` field.
 * The Promise ALWAYS resolves — connection/auth failures use { success: false }.
 */
export interface ImapConnectionResult {
  success: boolean
  error?: string
  /**
   * Categorized error type: "connection_refused" | "timeout" | "tls_error" |
   * "auth_failed" | "unknown". Present only when success is false.
   */
  errorType?: string
  /**
   * Detected IMAP capabilities: subset of "idle", "condstore", "qresync",
   * "compress", "namespace", "xoauth2", "gmail". Present only on success.
   */
  capabilities?: Array<string>
}

/**
 * IMAP sub-result within AccountValidationResult.
 *
 * Mirrors IMAPConnectionResult but as a separate type for the validate API.
 */
export interface ImapSubResult {
  success: boolean
  error?: string
  errorType?: string
  capabilities?: Array<string>
}

/**
 * Full provider info returned by providerForEmail.
 *
 * Matches the MailProviderInfo TypeScript interface.
 */
export interface MailProviderInfo {
  identifier: string
  servers: ProviderServers
  domainMatch: Array<string>
  mxMatch: Array<string>
}

/**
 * Connection settings for a single IMAP/SMTP/POP server.
 *
 * Field names use snake_case in Rust; napi-rs auto-converts to camelCase for JavaScript
 * (connection_type → connectionType).
 */
export interface NetServiceInfo {
  hostname: string
  /** napi-rs maps u32 to JavaScript number safely. Do NOT use u16. */
  port: number
  connectionType: string
}

/**
 * Look up the mail provider for a given email address.
 *
 * - Returns a provider object when a domain-match is found.
 * - Returns null when the email is valid but no provider matches.
 * - Throws a JS Error when email is empty or missing '@'.
 */
export declare function providerForEmail(email: string): MailProviderInfo | null

/** Grouped server lists for a mail provider. */
export interface ProviderServers {
  imap: Array<NetServiceInfo>
  smtp: Array<NetServiceInfo>
  pop: Array<NetServiceInfo>
}

/**
 * Load additional providers from a JSON file and merge them into the existing set.
 *
 * File providers win on identifier conflict (file overrides embedded).
 * Newly-seen identifiers are appended.
 */
export declare function registerProviders(jsonPath: string): void

/** Server connection info returned in AccountValidationResult. */
export interface ServerInfo {
  hostname: string
  port: number
}

/**
 * Options for testSMTPConnection.
 *
 * Field names use snake_case in Rust; napi-rs auto-converts to camelCase for
 * JavaScript (connection_type → connectionType, oauth2_token → oauth2Token).
 */
export interface SmtpConnectionOptions {
  hostname: string
  /** Port number as u32 (napi-rs maps u32 to JavaScript number safely). */
  port: number
  /** Connection type: "tls" | "starttls" | "clear". Defaults to "tls" if absent. */
  connectionType?: string
  username?: string
  password?: string
  /** OAuth2 bearer token for XOAUTH2 SASL authentication. */
  oauth2Token?: string
}

/**
 * Result of testSMTPConnection.
 *
 * The Promise ALWAYS resolves — connection/auth failures use { success: false }.
 */
export interface SmtpConnectionResult {
  success: boolean
  error?: string
  /**
   * Categorized error type: "connection_refused" | "timeout" | "tls_error" |
   * "auth_failed" | "unknown". Present only when success is false.
   */
  errorType?: string
}

/** SMTP sub-result within AccountValidationResult. */
export interface SmtpSubResult {
  success: boolean
  error?: string
  errorType?: string
}

/**
 * Test an IMAP connection with the provided settings.
 *
 * - Handles three connection modes: TLS (default), STARTTLS, and clear.
 * - Authenticates with either password (LOGIN) or OAuth2 (XOAUTH2 SASL).
 * - Detects 7 IMAP server capabilities post-login.
 * - Wraps the entire operation in a 15-second timeout.
 * - Always resolves the Promise — never rejects for connection/auth failures.
 *   Failures are returned as `{ success: false, error: "...", errorType: "..." }`.
 *
 * CRITICAL: `js_name` must be "testIMAPConnection" (all-caps IMAP) to match
 * the C++ export name that TypeScript callers use. Without js_name, napi-rs
 * auto-converts `test_imap_connection` to `testImapConnection` (lowercase).
 */
export declare function testIMAPConnection(opts: ImapConnectionOptions): Promise<ImapConnectionResult>

/**
 * Test an SMTP connection with the provided settings.
 *
 * - Handles three connection modes: TLS (default), STARTTLS, and clear.
 * - Authenticates with either password (LOGIN) or OAuth2 (XOAUTH2 SASL).
 * - Wraps the entire operation in a 15-second timeout.
 * - Always resolves the Promise — never rejects for connection/auth failures.
 *   Failures are returned as `{ success: false, error: "...", errorType: "..." }`.
 *
 * CRITICAL: `js_name` must be "testSMTPConnection" (all-caps SMTP) to match
 * the expected export name. Without js_name, napi-rs auto-converts
 * `test_smtp_connection` to `testSmtpConnection` (lowercase 'mtp').
 */
export declare function testSMTPConnection(opts: SmtpConnectionOptions): Promise<SmtpConnectionResult>

/**
 * Validate an email account by testing IMAP and SMTP connections concurrently.
 *
 * - Runs IMAP test, SMTP test, and MX DNS lookup in parallel via tokio::join!()
 * - Total time equals max(IMAP, SMTP, MX) — not their sum
 * - Wraps the entire operation in a 15-second timeout
 * - Always resolves the Promise — never rejects
 *
 * Result shape:
 * - success: true only when both IMAP and SMTP pass
 * - error/errorType: from the failing protocol (IMAP takes priority when both fail)
 * - identifier: provider identifier from MX match, or null
 * - imapResult/smtpResult: sub-results with their own success/error/errorType
 * - imapServer/smtpServer: the hostname+port used for testing
 */
export declare function validateAccount(opts: ValidateAccountOptions): Promise<AccountValidationResult>

/**
 * Options for validateAccount.
 *
 * Contains both IMAP and SMTP settings plus per-protocol auth credentials.
 */
export interface ValidateAccountOptions {
  email: string
  imapHostname: string
  imapPort: number
  imapConnectionType?: string
  imapUsername?: string
  imapPassword?: string
  smtpHostname: string
  smtpPort: number
  smtpConnectionType?: string
  smtpUsername?: string
  smtpPassword?: string
  oauth2Token?: string
}
