/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Full provider info returned by providerForEmail.
 *
 * Matches the MailProviderInfo TypeScript interface.
 */
export interface MailProviderInfo {
  identifier: string
  servers: ProviderServers
  domainMatch: Array<string>
  mxMatch: Array<string>
}

/**
 * Connection settings for a single IMAP/SMTP/POP server.
 *
 * Field names use snake_case in Rust; napi-rs auto-converts to camelCase for JavaScript
 * (connection_type → connectionType).
 */
export interface NetServiceInfo {
  hostname: string
  /** napi-rs maps u32 to JavaScript number safely. Do NOT use u16. */
  port: number
  connectionType: string
}

/**
 * Look up the mail provider for a given email address.
 *
 * - Returns a provider object when a domain-match is found.
 * - Returns null when the email is valid but no provider matches.
 * - Throws a JS Error when email is empty or missing '@'.
 */
export declare function providerForEmail(email: string): MailProviderInfo | null

/** Grouped server lists for a mail provider. */
export interface ProviderServers {
  imap: Array<NetServiceInfo>
  smtp: Array<NetServiceInfo>
  pop: Array<NetServiceInfo>
}

/**
 * Load additional providers from a JSON file and merge them into the existing set.
 *
 * File providers win on identifier conflict (file overrides embedded).
 * Newly-seen identifiers are appended.
 */
export declare function registerProviders(jsonPath: string): void
